controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    gpio_controller:
      type: gpio_controllers/GpioCommandController

gpio_controller:
  ros__parameters:
    gpios:
      - xxx
    command_interfaces:
      xxx:
        - interfaces:
          - vacuum
          - camera
    state_interfaces:
      xxx:
        - interfaces:
          - run