controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

gpio_controller:
  ros__parameters:
    type: gpio_controllers/GpioCommandController
    gpios:
      - xxx
    command_interfaces:
      xxx:
        - interfaces:
          - led