controller_manager:
  ros__parameters:
    update_rate: 10  # Hz

    gpio_controller:
      type: gpio_controllers/GpioCommandController



gpio_controller:
  ros__parameters:
    gpios:
      # - flange_analog_IOs
      - flange_vacuum
    command_interfaces:
      # flange_analog_IOs:
        # - interfaces:
          # - analog_output1
      flange_vacuum:
        - interfaces:
          - vacuum